const busProperties = [
    "bus_number",
    "name", 
    "type", 
    "ac", 
    "sleeper", 
    "seater", 
    "volvo", 
    "source", 
    "destination", 
    "depart_time", 
    "arrival_time", 
    "boarding_point", 
    "array", 
    "dropping_point", 
    "array", 
    "duration", 
    "seat_fare", 
    "sleeper_fare", 
    "agent_seat_fare", 
    "agent_sleeper_fare", 
    "amenities", 
    "blanket", 
    "water_bottle", 
    "snacks", 
    "charging_point", 
    "movie", 
    "track_my_bus", 
    "emergency_contact", 
    "toilet", 
    "reschedulable", 
    "live_tracking", 
    "chart", 
    "running_days"]

export {busProperties}